#!/usr/bin/bash
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP="$(basename $SD)"
RD="$(dirname "$SD")"
machinectl poweroff $APP 2>/dev/null
sleep 1
rm -rf /var/lib/machines/$APP
rm -f /etc/systemd/nspawn/$APP.nspawn
rm -f $RD/$APP.passwd
