#!/usr/bin/bash
# get paths for scripts, the repo parent dir and app name
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP="$(basename $SD)"
RD="$(dirname "$SD")"
PASSWORD=creator
echo $PASSWORD>$RD/$APP.passwd
cp -rfpu $RD/debian /var/lib/machines/$APP
mkdir /var/lib/machines/$APP/app
cp $SD/nspawn /etc/systemd/nspawn/$APP.nspawn
sed -i 's/\r$//' /etc/systemd/nspawn/$APP.nspawn
cp $SD/certrenew.sh /var/lib/machines/$APP/app/certrenew.sh
chmod +x /var/lib/machines/$APP/app/certrenew.sh
cp $SD/certrenew.service /etc/systemd/system/certrenew.service
cp $SD/certrenew.timer /etc/systemd/system/certrenew.timer
# Strip Windows CRLF line endings that break script execution
sed -i 's/\r$//' /var/lib/machines/$APP/app/certrenew.sh
sed -i 's/\r$//' /etc/systemd/system/certrenew.service
sed -i 's/\r$//' /etc/systemd/system/certrenew.timer
systemd-nspawn --pipe -q -D /var/lib/machines/$APP /usr/bin/bash << EOF
	. /etc/bash.bashrc
	echo -e "$PASSWORD\n$PASSWORD" | passwd
	echo "$APP">/etc/hostname

	apt update
	apt -y install --no-install-suggests git certbot gpg curl openssl

	# build and install nostr key generator helper
	git clone https://github.com/jeremyd/npub2hex.git /npub2hex
	cd /npub2hex
	/usr/local/go/bin/go build
	cp npub2hex /usr/local/bin/npub2hex
EOF
systemctl stop systemd-nspawn@$APP
